name: hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  hello:
    runs-on: ubunto-latest
    stesps:
      - uses: actions/checkout@v2
      - name: hello_world
        run: echo "hello world"
        shell: bash

  goodbye:
    runs_on: ubunto-latest
    steps:
      - name: goodbye World
        run: echo "Goodbye world" 
        shell: bash

          
